server {
    listen       80;
    server_name  localhost;

    # gzip 压缩
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_min_length 256;

    # 静态文件
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        # SPA 路由回退
        try_files $uri $uri/ /index.html;
    }
}
